import { IMAGES } from '../images';

export const BEST_PRODUCTS = [
  { id: 'b1', name: "내추럴 린넨 데일리 셔츠", price: "45,000원", image: IMAGES.best1, reviews: 16, category: 'best', rank: 1 },
  { id: 'b2', name: "에센셜 데님 숏 점퍼", price: "63,000원", image: IMAGES.best2, reviews: 96, category: 'best', rank: 2 },
  { id: 'b3', name: "모던 실키 블라우스", price: "52,000원", image: IMAGES.best3, reviews: 45, category: 'best', rank: 3 },
  { id: 'b4', name: "뿌띠 리본 가방 ", price: "48,000원", image: IMAGES.best4, reviews: 32, category: 'best', rank: 4 },
  { id: 'b5', name: "데일리 모던 셔츠", price: "39,000원", image: IMAGES.best5, reviews: 120, category: 'best', rank: 5 },
  { id: 'b6', name: "클래식 배색 가디건", price: "59,000원", image: IMAGES.best6, reviews: 56, category: 'best', rank: 6 },
  { id: 'b7', name: "베이직 벨트 슬랙스", price: "128,000원", image: IMAGES.best7, reviews: 210, category: 'best', rank: 7 },
  { id: 'b8', name: "소프트 브이넥 니트", price: "59,000원", image: IMAGES.best8, reviews: 88, category: 'best', rank: 8 },
  { id: 'b9', name: "베이직 린넨 가방", price: "65,000원", image: IMAGES.best9, reviews: 34, category: 'best', rank: 9 },
  { id: 'b10', name: "플리트 롱 스커트 ", price: "158,000원", image: IMAGES.best10, reviews: 15, category: 'best', rank: 10 },
  { id: 'b11', name: "슬림 골지 나시", price: "42,000원", image: IMAGES.best11, reviews: 67, category: 'best', rank: 11 },
  { id: 'b12', name: "빈티지 워싱 데님 스커트 ", price: "54,000원", image: IMAGES.best12, reviews: 92, category: 'best', rank: 12 },
  { id: 'b13', name: "타이 포인트 실크 블라우스", price: "58,000원", image: IMAGES.best13, reviews: 41, category: 'best', rank: 13 },
  { id: 'b14', name: "와이드 모던 슬랙스", price: "72,000원", image: IMAGES.best14, reviews: 28, category: 'best', rank: 14 },
  { id: 'b15', name: "어반 테이퍼드 와이드 슬랙스", price: "49,000원", image: IMAGES.best15, reviews: 156, category: 'best', rank: 15 },
  { id: 'b16', name: "여리핏 골지 니트 나시", price: "45,000원", image: IMAGES.best16, reviews: 73, category: 'best', rank: 16 },
  { id: 'b17', name: "미니멀 탄탄 점퍼", price: "39,000원", image: IMAGES.best17, reviews: 84, category: 'best', rank: 17 },
  { id: 'b18', name: "셔링 타이 실크 블라우스", price: "52,000원", image: IMAGES.best18, reviews: 59, category: 'best', rank: 18 },
  { id: 'b19', name: "프렌치 시크 블라우스", price: "86,000원", image: IMAGES.productBlouse, reviews: 42, category: 'best', rank: 19 },
  { id: 'b20', name: "쿨링 와이드 밴딩 슬랙스", price: "38,000원", image: IMAGES.productSlacks, reviews: 128, category: 'best', rank: 20 },
  { id: 'b21', name: "퍼프 소매 스퀘어넥 원피스", price: "69,000원", image: IMAGES.productDress, reviews: 75, category: 'best', rank: 21 },
  { id: 'b22', name: "벨티드 린넨 하프 자켓", price: "145,000원", image: IMAGES.newJacket, reviews: 31, category: 'best', rank: 22 },
  { id: 'b23', name: "쁘띠 실크 스카프 에디션", price: "24,000원", image: IMAGES.newScarf, reviews: 198, category: 'best', rank: 23 },
  { id: 'b24', name: "언밸런스 플리츠 롱 스커트", price: "56,000원", image: IMAGES.newSkirt, reviews: 64, category: 'best', rank: 24 },
  { id: 'b25', name: "미니멀 스퀘어 토트백", price: "112,000원", image: IMAGES.newBag, reviews: 22, category: 'best', rank: 25 },
  { id: 'b26', name: "볼륨 자수 레이닝 셔츠", price: "58,000원", image: IMAGES.bestItem1, reviews: 89, category: 'best', rank: 26 },
  { id: 'b27', name: "슬림 일자핏 생지 데님", price: "49,500원", image: IMAGES.bestItem2, reviews: 112, category: 'best', rank: 27 },
  { id: 'b28', name: "여리핏 골지 시계", price: "93,000원", image: IMAGES.recItem1, reviews: 345, category: 'best', rank: 28 },
  { id: 'b29', name: "골지 롱 슬릿 가디건", price: "89,000원", image: IMAGES.recItem2, reviews: 14, category: 'best', rank: 29 },
  { id: 'b30', name: "옥스포드 라운드 니트", price: "35,000원", image: IMAGES.productLinenShirt, reviews: 267, category: 'best', rank: 30 },
  { id: 'b31', name: "시스루 셔링 쉬폰 블라우스", price: "47,000원", image: IMAGES.productBlouse, reviews: 53, category: 'best', rank: 31 },
  { id: 'b32', name: "핀턱 코튼 배기 팬츠", price: "43,000원", image: IMAGES.productSlacks, reviews: 81, category: 'best', rank: 32 },
  { id: 'b33', name: "백리스 스트랩 롱 원피스", price: "82,000원", image: IMAGES.productDress, reviews: 39, category: 'best', rank: 33 },
  { id: 'b34', name: "오버사이즈 울 체크 자켓", price: "210,000원", image: IMAGES.newJacket, reviews: 18, category: 'best', rank: 34 },
  { id: 'b35', name: "패턴 드로잉 실크 머플러", price: "32,000원", image: IMAGES.newScarf, reviews: 124, category: 'best', rank: 35 },
  { id: 'b36', name: "머메이드 라인 데님 스커트", price: "46,000원", image: IMAGES.newSkirt, reviews: 92, category: 'best', rank: 36 },
  { id: 'b37', name: "캔버스 콤비 레더 버킷백", price: "89,000원", image: IMAGES.newBag, reviews: 47, category: 'best', rank: 37 },
  { id: 'b38', name: "프릴 넥 도트 블라우스", price: "54,000원", image: IMAGES.bestItem1, reviews: 66, category: 'best', rank: 38 },
  { id: 'b39', name: "와이드 롤업 생지 팬츠", price: "51,000원", image: IMAGES.bestItem2, reviews: 78, category: 'best', rank: 39 },
  { id: 'b40', name: "골드 체인 목걸이", price: "28,000원", image: IMAGES.recItem1, reviews: 156, category: 'best', rank: 40 },
  { id: 'b41', name: "노카라 미니멀 린넨 가디건", price: "135,000원", image: IMAGES.recItem2, reviews: 25, category: 'best', rank: 41 },
  { id: 'b42', name: "스트라이프 오버핏 라운드 니트", price: "44,000원", image: IMAGES.productLinenShirt, reviews: 189, category: 'best', rank: 42 },
  { id: 'b43', name: "소매 디테일 화이트 셔츠", price: "59,000원", image: IMAGES.productBlouse, reviews: 41, category: 'best', rank: 43 },
  { id: 'b44', name: "밴딩 조거 코튼 팬츠", price: "36,000원", image: IMAGES.productSlacks, reviews: 213, category: 'best', rank: 44 },
  { id: 'b45', name: "플리츠 믹스 니트 원피스", price: "95,000원", image: IMAGES.productDress, reviews: 32, category: 'best', rank: 45 },
  { id: 'b46', name: "클래식 더블 버튼 트렌치", price: "248,000원", image: IMAGES.newJacket, reviews: 12, category: 'best', rank: 46 },
  { id: 'b47', name: "빈티지 플라워 쁘띠 스카프", price: "18,000원", image: IMAGES.newScarf, reviews: 312, category: 'best', rank: 47 },
  { id: 'b48', name: "A라인 레더 미니 스커트", price: "53,000원", image: IMAGES.newSkirt, reviews: 54, category: 'best', rank: 48 },
  { id: 'b49', name: "데일리 크로스 바디 백", price: "67,000원", image: IMAGES.newBag, reviews: 88, category: 'best', rank: 49 },
  { id: 'b50', name: "컬러 블록 기본 셔츠", price: "62,000원", image: IMAGES.bestItem1, reviews: 71, category: 'best', rank: 50 },
];
